### ISSUE TITLE
Feature request: Multiple targets

### ISSUE THREAD

**Issue by vergissberlin** [MacroYau/arduino-cli-compile-docker#2]
Hi!

... and thank you to share your code! 

It would be nice if your compiler support multiple targets like so:

```yml
targets:
  - name: esp32
    core: esp32:esp32
    board: esp32:esp32:d1_mini3
    url: https://dl.espressif.com/dl/package_esp32_index.json
  - name: esp8266
    core: esp8266:esp8266
    board: esp8266:esp8266:generic
    url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
```

Is tough to implement?

kind regards
André
